<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<p>
The <a target="_blank" href="http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/DataStore">
Slicer Data Store</a> is hosted by <a target="_blank" href="http://www.kitware.com">Kitware<a> using 
<a target="_blank" href="http://midasplatform.org">Midas Platform</a>.
The Data Store Catalog can also be accessed via your web browser
<a target="_blank" href="http://slicer.kitware.com/midas3/slicerdatastore">here</a>.
</p>

<p>
  <B>Kitware</b> offers support and consulting services to aid software development and provide expert solutions around <b>open-source</b> software including <b>VTK, ParaView, CMake, ITK, and 3D Slicer</b>. Do not hesitate to contact us at</p>
<center>
  <a target="_blank" href="mailto:kitware@kitware.com">kitware@kitware.com</a>
</center>

<center style="margin-top:1.1em">
  <a style="margin: 0 5px 0 5px;" target="_blank" href="http://www.midasplatform.org"><img
    src="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore/public/images/midas48.png"/></a>
</center>

<br/>
<center>
<small>
This work was supported by NIH Grant 3P41RR013218-12S1, NA-MIC, NAC, and the Slicer community.
</small>
</center>