<?php
/* =========================================================================
  MIDAS Server
  Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
  69328 Lyon, FRANCE.

  See Copyright.txt for details.
  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notices for more information.
  ========================================================================= */


$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/jquery.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/jquery-ui.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.empty.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.callback.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.notice.js');
$this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/upload/upload.index.js');
echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Login</title>
    <meta name="robots" content="index, follow, all" />
    <!-- Import CSS -->
    <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore/public/css/user/user.loginform.css" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />
    <?php
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/jquery.qtip.min.css" />';
    ?>

    <?php echo $this->headLink();  // import the css ?>
    <?php echo $this->headStyle(); // import the css ?>

  </head>
  <body>
    <div id="modalDialog" style="display:none;"></div>
    <div style="display:none;" class="Wrapper"></div>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot . "/" . $this->moduleParent ?>/slicerdatastore/public/css/user/user.login.css" />
    <div class="loginElement">
      <form id="loginForm"  style="margin-left: 18px;">
      <h1 style="font-size: 16px;color: #333;text-shadow: rgba(0, 0, 0, 0.46) 1px 1px 1px;margin-top: 0px;">Upload Current Dataset</h1>
      
      <?php
      if($this->item)
        {
        ?>
        <p>Dataset: <?php echo $this->item->getName()?></p>
        <label for="changes">Changes</label><br/>
        <input type="text" id="changes"/><br/>
      <?php
        }
      else
        {
        ?>
        <label for="name">Name</label><br/>
        <input type="text" id="nameResource"/><br/>
        <label for="category">Category</label><br/> <input  type="text" id="categoryResource"/>
      <?php
        }
        ?>

      <br/>
      <br/>
      <input type="submit" class="globalButton " id="submitButton" value="Start the Upload"/>
      </form>
      <?php
      if($this->item)
        {
        echo "<br/><a style='color: #56758b;text-decoration:none;' href='".$this->webroot."/slicerdatastore/view?itemId=".$this->item->getKey()."'>Back</a><br/>";
        }
      ?>
    </div>
    
    <div style="display: none;" class="jsonContent">
      <?php echo $this->json ?>
    </div>
  </body>
  <?php echo $this->headScript();
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.qtip.min.js"></script>';?>
</html>