<?php
/* =========================================================================
  MIDAS Server
  Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
  69328 Lyon, FRANCE.

  See Copyright.txt for details.
  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notices for more information.
  ========================================================================= */
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/jquery.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/jquery-ui.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.empty.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.callback.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/midas.notice.js');
$this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/common/common.js?v='.VERSION_CACHE);
$this->headScript()->appendFile($this->webroot . "/" . $this->moduleParent . '/slicerdatastore/public/js/upload/upload.index.js');
$this->headScript()->appendFile($this->webroot . "/" . $this->moduleParent . '/slicerdatastore/public/js/ckeditor/ckeditor.js');
echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
    <meta name="robots" content="index, follow, all" />
    <!-- Import CSS -->
    <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot . "/" . $this->moduleParent ?>/slicerdatastore/public/css/user/user.loginform.css" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot . "/" . $this->moduleParent ?>/slicerdatastore/public/css/upload/upload.index.css" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore/public/css/index/index.index.css?v=<?php echo VERSION_CACHE?>" />

    <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/layout/jquery-ui.css" />
    <?php
    echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery.qtip.min.css" />';
    ?>

    <?php echo $this->headLink();  // import the css ?>
    <?php echo $this->headStyle(); // import the css ?>

  </head>
  <body>
    <div id="modalDialog" style="display:none;"></div>
    <div style="display:none;" class="Wrapper"></div>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot . "/" . $this->moduleParent ?>/slicerdatastore/public/css/user/user.login.css" />
    <div class="loginElement">
      <form id="loginForm"  style="margin-left: 18px;">
        <div style="float:right;">
          <?php if($this->logged) { ?>
            <div class="logoutDiv"><a href="javascript:;" id="logoutLink">Logout</a></div>
          <?php } ?>
        </div>
        <h1 style="font-size: 16px;color: #333;text-shadow: rgba(0, 0, 0, 0.46) 1px 1px 1px;margin-top: 0px;">
          <?php echo (isset($_GET['edit']))? "Edit Dataset":"Upload Current Dataset"?></h1>

        <div class="formElement" <?php echo (isset($_GET['revision']))? "style='display:none;'":""?>>
          <label for="name">Name</label><br/>
          <input style="width:100%;" type="text" id="nameResource" <?php if($this->item) echo 'value="'.$this->item->getName().'"';?>/>
        </div>
        <div class="formElement" <?php echo (isset($_GET['edit']) || !$this->item)? "style='display:none;'" : ""?>>
          <label for="name">Changes</label><br/>
          <input style="width:100%;" type="text" id="changeResource" value=''/>
        </div>
        <div class="formElement"  <?php echo (isset($_GET['revision']))? "style='display:none;'":""?>>
          <label style="margin-top:10px;" for="category">Categories</label><br/>
          <?php
          if(empty($this->categories))
            {
            echo '<input style="width:250px;"  type="text" class="categoryResource"/>';
            }
          else
            {
            foreach($this->categories as $category)
              {
              echo '<input style="width:250px;"  type="text" class="categoryResource" value="'.$category.'"/>';
              }
            }
          ?>
        </div>
        <a id="addACategory">Add a Category</a>
        <div class="formElement">
          <label for="description">Additional Description</label>
          <textarea class="ckeditor" name="description" id="description" style=""><?php echo $this->description?></textarea>
        </div>
        <br/>
        <?php
        if ($this->item)
          {
          echo "<a  id='backLink' href='" . $this->webroot . "/slicerdatastore/view?itemId=" . $this->item->getKey() . "'>Back</a> ";

          if(isset($_GET['edit']))echo '<input type="submit" class="globalButton " id="submitEditButton" value="Edit Metadata"/>';
          else echo '<input type="submit" class="globalButton " id="submitButton" value="Upload a new revision"/>';
          }
        else
          {
          echo '<input type="submit" class="globalButton " id="submitButton" value="Start the Upload"/>';
          }
        ?>

      </form>

    </div>
    <?php
    if(!empty($this->ownedItems))
      {
      ?>
      <br/>
      <div class="loginElement" style="min-height: 1px!important">
        <h1 style="font-size: 16px;color: #333;text-shadow: rgba(0, 0, 0, 0.46) 1px 1px 1px;margin-top: 0px;">
          Upload a new revision of an existing dataset:</h1>
        <div id="listDatasets"></div>
        <div style="clear:both;"><div>
      </div>
    <?php
      }
      ?>

    <div style="display: none;" class="jsonContent">
      <?php echo $this->json ?>
    </div>
       <!-- TEMPLATE: extension -->
    <div class="extensionWrapper" style="display: none;" id="extensionTemplate">
      <div class="extensionIconWrapper">
        <img  alt="" src="" class="extensionIcon" />
      </div>
      <div class="extensionNameWrapper">
        <span class="extensionName"></span>
      </div>
      <div class="subtitleWrapper">
        <span class="subtitle"></span>
      </div>       
    </div>            

  </body>
  <?php echo $this->headScript();
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.qtip.min.js"></script>';
  ?>
</html>