<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

function makeClickableLinks($string){
  /*** make sure there is an http:// on all URLs ***/
  $string = preg_replace("/([^\w\/])(www\.[a-z0-9\-]+\.[a-z0-9\-]+)/i", "$1http://$2",$string);
  /*** make all URLs links ***/
  $string = preg_replace("/([\w]+:\/\/[\w-?&;#~:=\.\/\@]+[\w\/])/i","<a class='generatedLink' href=\"$1\">$1</A>",$string);
  /*** make all emails hot links ***/
  $string = preg_replace("/([\w-?&;#~=\.\/]+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,3}|[0-9]{1,3})(\]?))/i","<A HREF=\"mailto:$1\">$1</A>",$string);
  return $string;
}


echo $this->doctype();
        

?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Datasets</title>
  <meta name="robots" content="index, follow, all" />
  <!-- Import CSS -->
  <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore/public/css/common/common.css?v=<?php echo VERSION_CACHE?>" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore//public/css/view/view.index.css?v=<?php echo VERSION_CACHE?>" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore//public/css/lightbox/jquery.lightbox-0.5.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot."/".$this->moduleParent?>/slicerdatastore//public/css/imgliquid/imgLiquid.js.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery.qtip.min.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.jqplot.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery.qtip.min.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/star_rating/jquery.ui.stars.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/comments/public/css/item/item.comments.css" />
  <link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/item/item.ratings.css" />

  <?php echo $this->headLink();  // import the css ?>
  <?php echo $this->headStyle(); // import the css ?>

</head>
<body>
  <div id="modalDialog" style="display:none;"></div>
  <div class="MainDialog" style="display:none;">
    <div class="MainDialogContent">
    </div>
    <div class="MainDialogLoading">
      <img alt="" src="<?php echo $this->coreWebroot;?>/public/images/icons/loading.gif" />
    </div>
    <input type="hidden" class="DialogContentPage"/>
  </div>

  <div class="category">
  <span id="categoryBreadcrumb">
    <a id="rootBreadcrumb" class="breadcrumbLink" href="">Datasets</a>
  </span>
</div>

<div id="container_main">
  <div id="extension_banner">
    <div class="title">
      <div class="extension_title"><?php echo $this->item->getName()?></div>
      <div class="group_title">
        <?php if($this->contributor) echo $this->contributor ?>
      </div>
    </div>
    <div class="button_bar">
      <?php if($this->logged) { ?>
        <div class="logoutDiv"><a href="javascript:;" id="logoutLink">Logout</a></div>
      <?php } ?>
    </div>
  </div>
  <div class="left_column">
    <div class="extensionIconWrapper">
        <img  alt="" src="<?php echo $this->webroot ?>/item/thumbnail?itemId=<?php echo $this->item->getKey()?>" class="extensionIcon" />
    </div>

    <div class="extensionActionButtonWrapper">
      <input type="button" class="extensionActionButton" value=""/>
    </div>
    <div class="info_list">
      <div class="info_item">
        Created <?php echo date('F j, Y', strtotime($this->item->getDateCreation())); ?>
      </div>
      <div class="info_item">
        <?php echo UtilityComponent::formatSize($this->item->getSizebytes()); ?>
      </div>
      <div class="info_item">
        <?php echo $this->item->getDownload() ?> downloads
      </div>
        <div class="info_item">
          <a style="color:#56758b;cursor:pointer;" id="datasetUrl">View dataset URL</a>
          <div id="dialogUrl" title="Dataset: <?php echo $this->item->getName()?>" style="display:none;">
            <p>
              The following URL points to the current dataset's page. This URL will remain unchanged allowing you to share it.
            </p>
            <input style="width:400px;" type="text" value="<?php echo UtilityComponent::getServerURL().$this->webroot?>/slicerdatastore/view?itemId=<?php echo $this->item->getKey()?>" class="field left" readonly>
          </div>          
        </div>
        <?php
        if($this->lastRevision->getRevision() != 2)
          {
          echo '<div class="info_item">';
          echo '<a style="color:#56758b;cursor:pointer;" id="revisionLink">View the revisions</a>';
          echo '<div id="dialogRevision" title="Revisions" style="display:none;">';
          echo "<table id='revisionTable'>";
          echo "<thead><tr><th>Revision</th><th>Date</th><th style='width:300px;'>Changes</th><th></th></tr></thead>";
          echo "<tbody>";
          for($i = $this->lastRevision->getRevision(); $i >1 ; $i--)
            {
            $revision = MidasLoader::loadModel("Item")->getRevision($this->item, $i);
            if(!$revision || !$revision->saved)continue;
            
            $bitstream = end($revision->getBitstreams());
            if(!$revision)continue;
            echo "<tr>";
            echo "<td>".($i-1)."</td>";
            echo "<td>".date("m/d/Y", strtotime($revision->getDate()))."</td>";
            if($i == 2) echo "<td>First revision</td>";
            else echo "<td>".$revision->getChanges()."</td>";
            echo '<td><div class="revisionActionButtonWrapper">  <input revision="'.$i.'" bitstream="'.$bitstream->getKey().'" type="button" class="revisionActionButton" value=""/> </div></td>';
            echo "</tr>";
            }
          echo "</tbody>";
          echo "</table>";
          echo "</div>";
          echo "</div>";
          }
          ?>
      <?php
      if($this->isOwner)
        {
        ?>
        <div class="info_item">
          <a style="color:#56758b;cursor:pointer;text-decoration: none;" href="<?php echo $this->webroot?>/slicerdatastore/upload?edit=true&itemId=<?php echo $this->item->getKey()?>">
            Edit metadata</a>
        </div>
        <div class="info_item">
          <a style="color:#56758b;cursor:pointer;text-decoration: none;" href="<?php echo $this->webroot?>/slicerdatastore/upload?revision=true&itemId=<?php echo $this->item->getKey()?>">
            Upload a new revision</a>
        </div>
        <div class="info_item">
          <a style="color:#56758b;cursor:pointer;" id="deleteDataSet">Delete the dataset</a>
        </div>
      <?php
        }
        ?>
    </div>
    <div class="rating_area">
      <?php echo $this->element('rating', 'ratings'); ?>
    </div>
    <div class="rating_scale">
    </div>
  </div>
  <div class="right_content">
    <?php
    if($this->homepage)
      { ?>
      <div class="content_header">
        Links
      </div>
      <div class="links">
        <?php
        echo '<div class="homepageContainer"><a href="'.$this->homepage.'">';
        echo '<img alt="" src="'.$this->webroot."/".$this->moduleParent.'/slicerdatastore/public/images/house_link.png" /> ';
        echo 'View home page</a></div>';
        ?>
      </div>
    <?php 
      } ?>
    <div class="content_header">
      Scenes (<?php echo count($this->metadata)?>):
    </div>
    <div class="screenshots" style="width:100%;">
      <ul>
      
      <?php
      foreach($this->metadata as $metadata)
        {
        echo "<li style='list-style: none;'>";
        echo "<div style='float:left; width:700px;margin:5px;'>";
        $url = $this->webroot."/slicerdatastore/view/download?bitstream=".array_search($metadata['id'], $this->screenshots);
        echo '<div style="display:none;" class="screenshotContainer">
                <a class="screenshotPreview" href="'.$url.'">
                  <img class="screenshotPreview"  src="'.$url.'">
                </a>
              </div>';
        echo "</td>";
        echo "<td>";
        echo "<b>".$metadata['name']."</b><br/>";
        echo makeClickableLinks($metadata['description']);
        echo "</div>";
        echo "</li>";
        }
      ?>
      </table>
    </div>
    
    <?php
    $strippedDescription = trim(strip_tags($this->description));
    if(!empty($strippedDescription))
      {?>    
      <div class="content_header">
        Description:
      </div>
      <div class="screenshots"  style="width:100%;">
        <?php echo $this->description?>
      </div>
    <?php
      }?>
    
    
    <div class="content_header">
      User Comments
    </div>
    <div class="reviews">
      <?php echo $this->element('comment', 'comments'); ?>
    </div>
  </div>
</div>


<!-- TEMPLATE: login form -->
<div id="loginFormTemplate" style="display:none;">
  <div class="loginError">
  </div>
  <form class="loginForm dialogForm" method="POST" action="<?php echo $this->webroot?>/user/ajaxlogin">
    <table>
      <tr><td>E-mail</td><td><input name="email" type="text" /></td></tr>
      <tr><td>Password</td><td><input name="password" type="password" /></td></tr>
      <tr><td></td><td><input type="submit" value="Login" /></td></tr>
    </table>
  </form>
  <div>
  Not registered? <a class="registerLink" href="javascript:;">Register</a>
  </div>
</div>

<!-- TEMPLATE: register form -->
<div id="registerFormTemplate" style="display:none;">
  <div class="registerError">
  </div>
  <form class="registerForm dialogForm" method="POST" action="<?php echo $this->webroot?>/user/ajaxregister">
    <table>
      <tr><td>E-mail</td><td><input name="email" type="text" /></td></tr>
      <tr><td>First Name</td><td><input name="firstname" type="text" /></td></tr>
      <tr><td>Last Name</td><td><input name="lastname" type="text" /></td></tr>
      <tr><td>Password</td><td><input name="password1" type="password" /></td></tr>
      <tr><td>Confirm Password</td><td><input name="password2" type="password" /></td></tr>
      <tr><td></td><td><input type="submit" value="Register" /></td></tr>
    </table>
  </form>
  <div>
  Already registered? <a class="loginLink" href="javascript:;">Login</a>
  </div>
</div>      


  <?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/jquery.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/jquery-ui.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.empty.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.callback.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.dialog.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.notice.js');  
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.jqplot.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.barRenderer.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.categoryAxisRenderer.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.pointLabels.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.autogrow-textarea.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/jquery.qtip.min.js');
  $this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/common/common.js?v='.VERSION_CACHE);
  $this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/view/view.index.js?v='.VERSION_CACHE);
  $this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/lightbox/jquery.lightbox-0.5.pack.js');
  $this->headScript()->appendFile($this->webroot."/".$this->moduleParent.'/slicerdatastore/public/js/imgliquid/imgLiquid-min.js');
  $this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/star_rating/jquery.ui.stars.min.js');
  $this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/common/common.ratings.js');
  $this->headScript()->appendFile($this->webroot.'/modules/comments/public/js/item/item.comments.js');

    
  ?>
  <?php echo $this->headScript() ?>
  <input type="hidden" class="webroot" value="<?php echo $this->webroot ?>" />
  <div style="display: none;" class="jsonContent">
    <?php echo $this->json ?>
  </div>
</body>

<?php
$footers = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_GET_FOOTER_LAYOUT', array());
if(!empty($footers))
  {
  foreach($footers as $footer)
    {
    echo $footer;
    }
  }
?>
</html>


